### ISSUE TITLE
无法更换QQ号？

### ISSUE THREAD

**Issue by wegood9** [qq519043202/Head-inform#2]
自带的QQ可以获取头像，但是换上我自己的QQ号后无法使用，出现以下错误：
200
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    main()
  File "main.py", line 56, in main
    c1.run()
  File "main.py", line 50, in run
    raise e
KeyError: 'last-modified'

**Comment by Tmn07** [comment]
你好，可以提供一下你的qq号吗。我这里没有遇到你这样的情况。
目前邮件功能似乎出了一点问题，但是还是能够获取到头像的

**Comment by wegood9** [comment]
呃，我后来又测试了一下，只有一个QQ号有问题，头像为默认的企鹅，QQ号不便公布。其他的QQ号没问题，可以正常获取，同时也可以发邮件。
有个小问题：请问可以获取别人的历史QQ头像吗？

**Comment by Tmn07** [comment]
默认的头像可能没有返回的heade里可能没有'last-modified'字段、所以没处理，就报错了。
我没有找到历史头像的接口，有的话可以搞
